name: test

on: 
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  ANALYZER_OUTPUT_FILE_NAME: analyze_output.txt

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      
      - name: Install Flutter
        id: flutter_install
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' 
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Cache apt-install
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: ninja-build libgtk-3-dev
        
      - name: Cache dependencies
        uses: actions/cache@v3.2.2
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.OS }}-pub-cache-${{ hashFiles('./pubspec.lock') }}
          restore-keys: ${{ runner.OS }}-pub-cache-
            
      - name: Install dependencies
        run: flutter pub get
          
      - name: Analyze code 
        run: flutter analyze --write=./${{ env.ANALYZER_OUTPUT_FILE_NAME }}
          
      - name: Artifacts analyze
        uses: actions/upload-artifact@v3.1.1
        if: failure()
        with:
          name: ${{ env.ANALYZER_OUTPUT_FILE_NAME }}
          path: ./${{ env.ANALYZER_OUTPUT_FILE_NAME }}
